/**
 * Echo AI — Question Generator v2
 *
 * Stage-aware, rotation-enforced, present-day-aware.
 * Every question is generated by Groq based on the user's
 * actual life. No hardcoded question bank.
 *
 * Flow:
 *   getTodaysQuestion(userId) [public]
 *     → checks user_question_log for today
 *     → if missing: fetches all previous answers + recent log
 *     → calls generateNextQuestion(userId, answers, total) [internal]
 *     → stores in log, returns { questionText, alreadyAnswered, logId }
 *
 * Stages: warmup → foundations → journey → depths → legacy
 * Rotation: ROTATION_RULES prevents same category back-to-back
 * Present-day: every ~4th question asks about current life (goals,
 *   struggles, what they're building NOW) — not just the past
 */

import { callGemini } from './gemini'
import { supabase }   from './supabase'

/* ═══════════════════════════════════════════════════════════
   STAGE DEFINITIONS
   range = [minAnswers, maxAnswers] inclusive
   categories = valid categories at this stage
   depth = 1-5 marker for the prompt
═══════════════════════════════════════════════════════════ */
const STAGES = {

  warmup: {
    range: [0, 3],
    categories: ['Family', 'Happiness', 'Identity'],
    depth: 1,
    instruction: `
Warm, easy, inviting. First question — make them smile, not think hard.
Ask about something specific and sensory from early life. Concrete, not abstract.

Examples of the RIGHT tone:
"What's a smell from your childhood that takes you straight back?"
"Who made you feel completely safe when you were growing up?"
"What's something simple you did as a kid that you still miss?"
"What did home look like when you were young?"
`,
  },

  foundations: {
    range: [4, 8],
    categories: ['Family', 'Relationships', 'Identity', 'Happiness'],
    depth: 2,
    instruction: `
A little deeper — the people and moments that shaped them.
Still warm and easy to answer. One clear, direct question.

Examples of the RIGHT tone:
"Who believed in you before you believed in yourself?"
"What did your parents always say that you hear yourself saying now?"
"What were you like at 16 that would surprise people who know you today?"
"Who's someone you've never properly thanked?"
`,
  },

  journey: {
    range: [9, 15],
    categories: ['Hardship', 'Wisdom', 'Relationships', 'Identity'],
    depth: 3,
    instruction: `
Real but not heavy. The pivots and turning points of their life.
Short question that hits something true and specific.

Examples of the RIGHT tone:
"What's the hardest yes you ever said?"
"What did you have to lose before you understood what mattered?"
"Which relationship changed you most — and how?"
"What's a decision that still sits with you?"
`,
  },

  depths: {
    range: [16, 24],
    categories: ['Regrets', 'Hardship', 'Relationships', 'Identity', 'Wisdom'],
    depth: 4,
    instruction: `
Honest and direct. Ask the thing most people never get asked.
Short, clear, personal — not heavy-handed. One question, no explanation.

Examples of the RIGHT tone:
"Who deserved more from you than you gave?"
"What do you still wish you'd said?"
"What version of your life do you think about sometimes?"
"What did you sacrifice that you still feel?"
`,
  },

  legacy: {
    range: [25, 9999],
    categories: ['Wisdom', 'Family', 'Identity', 'Happiness', 'Regrets'],
    depth: 5,
    instruction: `
What they'd want passed on. Sacred but not heavy — still personal and direct.

Examples of the RIGHT tone:
"What do you want the people who love you to know — that they probably don't?"
"What do you know now that you wish you'd figured out at 30?"
"What would surprise people most about who you really are?"
"What do you hope they remember when you're gone?"
`,
  },
}

/* ═══════════════════════════════════════════════════════════
   CATEGORY ROTATION RULES
   After asking about a category, rotate to something different.
   Maps lastCategory → recommended next categories (in priority order).
═══════════════════════════════════════════════════════════ */
const ROTATION_RULES = {
  Family:        ['Hardship', 'Identity', 'Wisdom', 'Regrets', 'Relationships'],
  Relationships: ['Hardship', 'Identity', 'Wisdom', 'Happiness', 'Family'],
  Hardship:      ['Wisdom',   'Identity', 'Happiness', 'Family', 'Relationships'],
  Happiness:     ['Hardship', 'Regrets',  'Wisdom',   'Identity', 'Relationships'],
  Wisdom:        ['Regrets',  'Relationships', 'Family', 'Happiness', 'Hardship'],
  Identity:      ['Regrets',  'Hardship', 'Relationships', 'Wisdom', 'Family'],
  Regrets:       ['Wisdom',   'Family',   'Happiness', 'Identity', 'Relationships'],
}

/* ═══════════════════════════════════════════════════════════
   STAGE-AWARE FALLBACKS
   Used ONLY if Groq is completely unavailable.
   One fallback per stage — never the same flat list.
═══════════════════════════════════════════════════════════ */
const STAGE_FALLBACKS = {
  warmup: [
    'What\'s a smell from your childhood that takes you straight back?',
    'Who made you feel completely safe when you were growing up?',
    'What\'s something simple you did as a kid that you still miss?',
  ],
  foundations: [
    'Who believed in you before you believed in yourself?',
    'What were you like at 16 that would surprise people who know you today?',
    'Who\'s someone you\'ve never properly thanked?',
  ],
  journey: [
    'What\'s the hardest yes you ever said?',
    'What did you have to lose before you understood what mattered?',
    'What\'s a decision that still sits with you?',
  ],
  depths: [
    'Who deserved more from you than you gave?',
    'What do you still wish you\'d said?',
    'What version of your life do you think about sometimes?',
  ],
  legacy: [
    'What do you want the people who love you to know — that they probably don\'t?',
    'What do you know now that you wish you\'d figured out at 30?',
    'What do you hope they remember when you\'re gone?',
  ],
}

/* ═══════════════════════════════════════════════════════════
   GENERAL FALLBACK BANK  (20 questions)
   Broader pool used alongside stage fallbacks when the API
   is offline, times out, or returns an empty response.
   Shown to user with a subtle "Question from our library" note.
═══════════════════════════════════════════════════════════ */
const GENERAL_FALLBACK_BANK = [
  // Family
  "What's something your parents did that you only understood years later?",
  "What's a story your family tells again and again?",
  "What did home feel like when you were young?",
  // Relationships
  "Who have you lost touch with that you still think about?",
  "Who showed up for you when it really counted?",
  // Hardship
  "What got you through the hardest stretch of your life?",
  "What did losing something teach you?",
  // Happiness
  "What's the simplest thing that's ever made you completely happy?",
  "Which ordinary moment would you step back into for just one hour?",
  // Wisdom
  "What's advice you received that took years to actually understand?",
  "What do you know now that you wish you'd known at 25?",
  // Identity
  "What do most people get wrong about you?",
  "What's a line you've never crossed — and what does that say about you?",
  "What would surprise people most about who you really are?",
  // Regrets
  "What's something you'd go back and do more slowly?",
  "What did you know was wrong but did anyway?",
  // Legacy
  "What do you hope they carry with them when you're gone?",
  // Present day
  "What's the most important thing in your life right now?",
  "What are you still trying to figure out about yourself?",
]

/* ─────────────────────────────────────────────────────────────
   withTimeout — wraps any promise with a max-duration guard.
   If the promise doesn't resolve within `ms`, rejects with
   a 'timeout' error which triggers the fallback bank.
───────────────────────────────────────────────────────────── */
function withTimeout(promise, ms) {
  return Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`timeout after ${ms}ms`)), ms)
    ),
  ])
}

/* ─────────────────────────────────────────────────────────────
   Helpers
───────────────────────────────────────────────────────────── */
function getCurrentStage(totalAnswers) {
  const entry = Object.entries(STAGES).find(
    ([, stage]) => totalAnswers >= stage.range[0] && totalAnswers <= stage.range[1]
  )
  return entry || ['legacy', STAGES.legacy]
}

function getNextCategory(lastCategory, stageCategories) {
  // Get rotation suggestions, filter to only stage-valid categories
  const suggestions = (ROTATION_RULES[lastCategory] || stageCategories)
    .filter(cat => stageCategories.includes(cat))
  const pool = suggestions.length > 0 ? suggestions : stageCategories
  return pool[Math.floor(Math.random() * pool.length)]
}

/* ═══════════════════════════════════════════════════════════
   PUBLIC API — getTodaysQuestion
   Same interface as v1: returns { questionText, alreadyAnswered, logId }
   Dashboard.jsx calls this without needing any changes.
═══════════════════════════════════════════════════════════ */
export async function getTodaysQuestion(userId) {
  const today = new Date().toISOString().split('T')[0]

  // 1. Is there already an unanswered question waiting?
  //    No date filter — questions flow continuously, not one-per-day.
  const { data: existing } = await supabase
    .from('user_question_log')
    .select('*')
    .eq('user_id', userId)
    .eq('question_type', 'main')
    .eq('answered', false)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (existing) {
    return {
      questionText:    existing.question_text,
      alreadyAnswered: false,
      logId:           existing.id,
      isFromLibrary:   false,
    }
  }

  // 2. Fetch all previous answers (we need category for rotation
  //    and the full set for Groq context — in chronological order)
  const { data: allAnswers } = await supabase
    .from('user_answers')
    .select('question_text, answer_text, category, created_at, depth_level')
    .eq('user_id', userId)
    .order('created_at', { ascending: true })

  const previousAnswers = allAnswers || []
  const totalAnswers    = previousAnswers.length

  // 3. Generate the question
  const { text: questionText, isFromLibrary } = await generateNextQuestion(userId, previousAnswers, totalAnswers)

  // 4. Store in log
  const { data: logEntry } = await supabase
    .from('user_question_log')
    .insert({
      user_id:       userId,
      question_text: questionText,
      asked_on:      today,
      answered:      false,
      question_type: 'main',
    })
    .select()
    .single()

  return {
    questionText,
    alreadyAnswered: false,
    logId:           logEntry?.id ?? null,
    isFromLibrary:   isFromLibrary || false,
  }
}

/* ═══════════════════════════════════════════════════════════
   INTERNAL — generateNextQuestion
   Core engine. Called only from getTodaysQuestion.
═══════════════════════════════════════════════════════════ */
async function generateNextQuestion(userId, previousAnswers, totalAnswers) {
  const [stageName, stage] = getCurrentStage(totalAnswers)

  // Last 3 questions asked — so Groq knows what topics to avoid
  const { data: recentLog } = await supabase
    .from('user_question_log')
    .select('question_text, asked_on')
    .eq('user_id', userId)
    .order('asked_on', { ascending: false })
    .limit(4) // fetch 4 since today's isn't logged yet — top 4 = last 3 answered

  const recentQuestions = (recentLog || []).map(q => q.question_text).slice(0, 3)

  // Rotation: pick next category based on last answer's category
  const lastAnswer   = previousAnswers[previousAnswers.length - 1]
  const lastCategory = lastAnswer?.category || 'Family'
  const nextCategory = getNextCategory(lastCategory, stage.categories)

  // Context: last 4 answers only (keeps prompt tight and fast)
  const recentContext = previousAnswers
    .slice(-4)
    .map(a =>
      `Question asked: "${a.question_text}"\n` +
      `Their answer: "${a.answer_text}"\n` +
      `Category: ${a.category}`
    )
    .join('\n\n')

  // Present-day questions: inject every 4th question (answer 4, 8, 12, 16…)
  // These ask about their CURRENT life — what they're building, struggling with,
  // working on, or trying to change RIGHT NOW — not just the past.
  const askPresentDay = totalAnswers > 0 && totalAnswers % 4 === 0

  // Warn about recent topics to avoid repetition
  const recentWarning = recentQuestions.length > 0
    ? `\nTOPICS ALREADY COVERED — DO NOT REVISIT THESE SUBJECTS:\n${recentQuestions.map((q, i) => `${i + 1}. "${q}"`).join('\n')}`
    : ''

  // Present-day instruction override — completely changes the question type
  const presentDayInstruction = askPresentDay ? `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SPECIAL RULE FOR THIS QUESTION:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This question MUST be about their life RIGHT NOW — not the past.
Ask about something happening in their current, present-day life:
- What they are building, creating, or working on right now
- What goal or ambition they are actively chasing at this stage
- What is challenging them most in their job, relationships, or life today
- What they are trying to figure out or change about themselves currently
- What they are most excited or anxious about in the near future
- What they wish someone understood about what they're going through right now

Make it feel like a check-in from a close friend who wants to know:
"How are you actually doing? What's taking up space in your head these days?"

It should be warm, direct, and feel like a genuine present-tense conversation —
not a memory exercise. People often only reflect on the PAST — this question
brings them INTO THE NOW and makes the archive feel alive.

Still target category: ${nextCategory}
` : ''

  const prompt = `You are preserving someone's complete life story — past AND present — for their family to treasure forever.

STAGE: ${stageName.toUpperCase()} (they have answered ${totalAnswers} question${totalAnswers !== 1 ? 's' : ''} so far)
TARGET CATEGORY: ${nextCategory}
LAST CATEGORY: ${lastCategory}
${recentWarning}

STAGE INSTRUCTIONS — match this depth exactly:
${stage.instruction}
${presentDayInstruction}

THEIR RECENT ANSWERS (context only — do not repeat these topics):
${recentContext || 'This is their very first question. No previous context.'}

══════════════════════════════════════
RULES — EVERY SINGLE ONE IS MANDATORY:
══════════════════════════════════════

RULE 1 — OPEN NEW GROUND EVERY TIME:
Do not revisit the same person, place, relationship, or subject
from any of the last 2–3 questions. Every question must open
a completely new door in their life story.
If they talked about grandfather → do NOT ask about grandfather again.
If they talked about childhood → move to adulthood, career, or relationships.

RULE 2 — ENFORCE CATEGORY ROTATION:
Last category: ${lastCategory}
Next category MUST be: ${nextCategory}
This is not optional. Pick something completely different in character.

RULE 3 — REFERENCE THEIR ANSWERS CORRECTLY (if referencing at all):
✗ WRONG: "You mentioned your grandfather — tell me more about him"
✓ RIGHT: "You said that complaining felt like a luxury — has there been
          a time in your own life where you had to hold that same standard?"
If you reference their past answers: use a SPECIFIC phrase or feeling
they mentioned, then redirect it to a NEW area of their life.
Never use someone's name or general topic as the hook.

RULE 4 — MATCH STAGE DEPTH EXACTLY:
Stage 1 (warmup): Light, safe, inviting
Stage 2 (foundations): Slightly deeper, formative
Stage 3 (journey): Real, challenging, pivotal
Stage 4 (depths): Honest, heavy, unflinching
Stage 5 (legacy): Profound, sacred, irreversible
You are at stage: ${stageName} (depth ${stage.depth}/5)

RULE 5 — SOUND HUMAN:
Short, direct, conversational — like a close friend asking, not a therapist or form.
No long clauses. No "and why do you think that" add-ons. Just the question.

RULE 6 — MAKE THEM FEEL IT IMMEDIATELY:
The question should land the moment they read it.
If it takes more than one read to understand, it's too complicated.
Short questions are more powerful than long ones.

RULE 7 — FORMAT (strict):
ONE sentence. Under 15 words is ideal. 20 words maximum.
No introduction. No preamble. No "Here is your question:".
Return ONLY the question text. Nothing else. No quotes around it.

Generate ONE question for category ${nextCategory} now.`

  try {
    const raw  = await withTimeout(callGemini(prompt), 8000)
    const text = raw
      .replace(/^["'`*"]+|["'`*"]+$/g, '')
      .replace(/^Here is (your|the) question[:\s]*/i, '')
      .trim()
    if (!text) throw new Error('empty response')
    return { text, isFromLibrary: false }
  } catch (err) {
    console.warn('[questionGenerator] API unavailable — using library fallback:', err.message)
    const stageFalls = STAGE_FALLBACKS[stageName] || STAGE_FALLBACKS.warmup
    const combined   = [...stageFalls, ...GENERAL_FALLBACK_BANK]
    const text       = combined[totalAnswers % combined.length]
    return { text, isFromLibrary: true }
  }
}

/* ═══════════════════════════════════════════════════════════
   PUBLIC API — getTodaysBonusQuestion
   Daily check-in question about TODAY's routine/moments.
   Only shown once user has at least 1 answered memory.
═══════════════════════════════════════════════════════════ */

const BONUS_FALLBACKS = [
  'What was the best part of your day today?',
  'Did you make time for someone you love today?',
  'What\'s one thing that happened today you want to remember?',
  'How are you feeling right now, honestly?',
  'Was there a moment today that surprised you?',
  'Who did you think about today?',
  'Did today feel like time well spent?',
  'What\'s something small that made today a little better?',
  'What are you grateful for from today?',
  'Was there something you wanted to say today but didn\'t?',
]

export async function getTodaysBonusQuestion(userId, recentMemories = []) {
  const today = new Date().toISOString().split('T')[0]

  // Already generated today's bonus?
  const { data: existing } = await supabase
    .from('user_question_log')
    .select('*')
    .eq('user_id', userId)
    .eq('asked_on', today)
    .eq('question_type', 'bonus')
    .maybeSingle()

  if (existing) {
    return {
      questionText:    existing.question_text,
      alreadyAnswered: existing.answered,
      logId:           existing.id,
    }
  }

  // Build context from the user's last 3 memories so the question feels personal
  const context = recentMemories
    .slice(0, 3)
    .map(m => `- "${m.answer_text.slice(0, 120)}"`)
    .join('\n')

  const prompt = `You are checking in with someone at the end of their day.
Based on what you know about them, ask ONE warm, personal question about their day TODAY — their routine, mood, small moments, people they were with, how they felt.

What you know about them (from their memories):
${context || '- No context yet'}

Write a question that feels like a close friend asking — short, direct, personal.
It should be about TODAY specifically: what happened, how they felt, who they were with, what they noticed.

Examples of the RIGHT tone:
"Did you make time for someone you love today?"
"What's one thing that happened today you want to remember?"
"Was there a moment today that felt like exactly where you should be?"
"How did today actually go?"
"What took up most of your headspace today?"

ONE sentence. Under 15 words. No quotes around it. Nothing else.`

  let questionText
  try {
    const raw = await withTimeout(callGemini(prompt), 6000)
    questionText = raw.replace(/^["'`*"]+|["'`*"]+$/g, '').trim()
    if (!questionText) throw new Error('empty')
  } catch {
    questionText = BONUS_FALLBACKS[new Date().getDate() % BONUS_FALLBACKS.length]
  }

  const { data: logEntry } = await supabase
    .from('user_question_log')
    .insert({
      user_id:       userId,
      question_text: questionText,
      asked_on:      today,
      answered:      false,
      question_type: 'bonus',
    })
    .select()
    .single()

  return {
    questionText,
    alreadyAnswered: false,
    logId:           logEntry?.id ?? null,
  }
}

/* ═══════════════════════════════════════════════════════════
   PUBLIC API — categorizeAnswer
   Same interface as v1. Returns one of the 7 valid categories.
═══════════════════════════════════════════════════════════ */
export async function categorizeAnswer(questionText, answerText) {
  const VALID = ['Family', 'Relationships', 'Hardship', 'Happiness', 'Wisdom', 'Identity', 'Regrets']

  const prompt = `Read this question and answer carefully.
Return ONLY one of these exact words — no punctuation, nothing else:
Family, Relationships, Hardship, Happiness, Wisdom, Identity, Regrets

Question: "${questionText}"
Answer: "${answerText.slice(0, 500)}"

Definitions:
Family        = relatives, parents, children, home life, family bonds
Relationships = friendships, romance, mentors, community, social bonds
Hardship      = struggle, loss, failure, adversity, pain, dark periods
Happiness     = joy, gratitude, peak moments, contentment, pride, love
Wisdom        = lessons learned, beliefs, philosophy, advice, understanding
Identity      = who they are, values, defining choices, self-discovery
Regrets       = things they wish were different, missed chances, what they'd change

One word only. Return it now.`

  try {
    const raw     = await callGemini(prompt)
    const cleaned = raw.trim().replace(/[^a-zA-Z]/g, '')
    return VALID.find(v => v.toLowerCase() === cleaned.toLowerCase()) ?? 'Wisdom'
  } catch {
    // Keyword fallback — only used if Groq completely fails
    const lower = answerText.toLowerCase()
    if (lower.match(/\b(mom|dad|family|sister|brother|grandma|grandpa|parent|child|son|daughter|home|relatives)\b/)) return 'Family'
    if (lower.match(/\b(friend|love|relationship|marriage|wife|husband|partner|mentor|community)\b/)) return 'Relationships'
    if (lower.match(/\b(hard|difficult|struggle|loss|fail|pain|grief|dark|scared|alone|crisis)\b/)) return 'Hardship'
    if (lower.match(/\b(happy|joy|best|wonderful|grateful|proud|beautiful|peace|excited|delight)\b/)) return 'Happiness'
    if (lower.match(/\b(learn|lesson|wisdom|advice|believe|understand|realize|truth|insight)\b/)) return 'Wisdom'
    if (lower.match(/\b(regret|wish|should have|mistake|wrong|if only|missed|never got to)\b/)) return 'Regrets'
    return 'Identity'
  }
}
